trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- checkout: self
  lfs: true
- task: Docker@1
  displayName: Build an image
  inputs:
    command: Build an image
    Dockerfile: dockerfile
- task: Docker@1
  displayName: Login
  inputs:    
     command: login
     containerRegistry: davidnohejldockerhub
- task: Docker@1
  displayName: 'Push an image'
  inputs:
     command: push an image
     imageName: 'metabolic-models:$(Build.BuildId)'