trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'metabolic-models'

steps:
- checkout: self
  lfs: true
- task: Docker@1
  displayName: Build an image
  inputs:
    command: Build an image
    Dockerfile: dockerfile
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:    
     command: login
     containerRegistry: davidnohejldockerhub

- task: Docker@2
  displayName: 'Push an image'
  inputs:
     command: push
     repository: davidnohejl/metabolic-models